### PR TITLE
Add translations for Simplified Chinese

### PR DESCRIPTION
**Pull request by beta**

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
@nguyenhoanglam Why not merging?

**Comment by nguyenhoanglam** [comment]
@Rainer-Lang the pull request is only valid with the old version. the new version has changed the string.xml file. so I did not merge this pull request.
It's would be great if everyone create new pull requests for version 1.2.0.

**Comment by beta** [comment]
@nguyenhoanglam Here you go: #73

**Comment by nguyenhoanglam** [comment]
@beta Thank you so much! Love you !

**Pull request closed without merging**
